<?php return array (
  'file_explan' => 
  array (
    'template|default|' => 
    array (
      'images' => '图片目录',
      'member' => '会员中心模板',
      'category_jiameng.html' => '',
      'category_news.html' => '新闻频道模板',
      'category_news2.html' => '',
      'category_pic.html' => '',
      'category_product.html' => '产品频道模板',
      'category_video.html' => '',
      'category_yfezx.html' => '',
      'config.php' => '模板备注文件',
      'content_download.html' => '',
      'footer.html' => '通用底部模板',
      'form.html' => '表单模板',
      'form~~.html' => '',
      'header.html' => '通用头部模板',
      'index.html' => '首页模板',
      'index原.html' => '',
      'left.html' => '内页左侧模板',
      'list_download.html' => '',
      'list_jiameng.html' => '',
      'list_news.html' => '新闻列表模板',
      'list_news2.html' => '',
      'list_pic.html' => '',
      'list_product.html' => '产品列表模板',
      'list_video.html' => '',
      'list_yfezx.html' => '',
      'page.html' => '单页面模板',
      'page2.html' => '',
      'page3.html' => '关于优范儿',
      'page4.html' => '',
      'page5.html' => '精彩瞬间',
      'post.html' => '',
      'search.html' => '搜索模板',
      'show_download.html' => '',
      'show_jiameng.html' => '',
      'show_news.html' => '新闻内容模板',
      'show_news2.html' => '',
      'show_pic.html' => '',
      'show_product.html' => '产品内容模板',
      'show_video.html' => '',
      'show_yfezx.html' => '',
      'sitemap.html' => '',
      'yytj.html' => '',
    ),
  ),
);?>